### PR TITLE
Speed up sync eng/common pipeline

### PR DESCRIPTION
**Pull request by benbp**
🏎️

### CODE REVIEW

**Review by mikeharder — APPROVED** [review]

**Comment by weshaggard** [comment]
@benbp after this change it seems like we are now lossing the test pipeline links in the posted comments. My best guess is the switch from windows to linux for some reason no longer correctly sets the output variable https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Queue-Pipeline.ps1#L118. Also the ps commands are no longer being dumped to the logs which sucks :(

**Comment by benbp** [comment]
@weshaggard ok let me take a look. I can revert in the meantime.

**Comment by sima-zhu** [comment]
@benbp https://github.com/Azure/azure-sdk-tools/pull/4701 I have a PR to test the fix. Unfortunately it is only logging the last one. Don't want to overlap with your work. Do you want to take over the fix?

**Comment by benbp** [comment]
@sima-zhu if you're testing out a fix that's great. I don't think I have much time to give it this week, so please continue!

**Pull request merged**
