### PR TITLE
[js-api-parser] don't add members as types

### PR DESCRIPTION
**Pull request by jeremymeng**
This PR uses the id of the token to determine whether it should be added as a member or a type.

### CODE REVIEW

**Comment by jeremymeng** [comment]
before: 
image
after: 
image

**Comment by jeremymeng** [comment]
Would this cause breaking changes to show up everywhere?

**Review by deyaaeldeen — APPROVED** [review]
LGTM, I am surprised there is no field that indicates membership

**Comment by jeremymeng** [comment]
> Would this cause breaking changes to show up everywhere?

@praveenkuttappan @chidozieononiwu?

**Comment by praveenkuttappan** [comment]
> > Would this cause breaking changes to show up everywhere?
> 
> @praveenkuttappan @chidozieononiwu?

Yes, unless we update the parser version and get all existing reviews updated. Can you please update JS parser version in following two locations.
https://github.com/Azure/azure-sdk-tools/blob/main/tools/apiview/parsers/js-api-parser/package.json#L3
https://github.com/Azure/azure-sdk-tools/blob/main/src/dotnet/APIView/APIViewWeb/Languages/JavaScriptLanguageService.cs#L14

This will upgrade all existing reviews using latest parser.

**Comment by jeremymeng** [comment]
@praveenkuttappan updated version number.  Looking good now?

**Review by praveenkuttappan — APPROVED** [review]
Looks good

**Pull request merged**
