### PR TITLE
Add '''@interface''' support

### LINKED ISSUE #219: Java APIView processor incorrectly handles annotations
Uploading azure-core demonstrates the issue - annotation types such as the `Immutable` type are listed as `public unknown Immutable`, rather than `public @interface Immutable`, and they do not list their fields properly either.

### PR DESCRIPTION
**Pull request by mssfang**
fixes #219

display 
```
@interface 
```
and support all fields in the side of custom annotation to be public

### CODE REVIEW

**Comment by JonathanGiles** [comment]
@pakrym Once this is merged, are you able to build and upload a new version of the jar file from the `target` directory?

**Comment by pakrym** [comment]
Yep, one day I would also setup CI pipeline do to it.

**Comment by JonathanGiles** [comment]
I don't have the ability to merge this PR. @pakrym or @mitchdenny, can you please merge?

**Comment by pakrym** [comment]
It's the check-enforcer-dev  bug again

**Pull request merged**
