### PR TITLE
Add Jump links from Models to Definitions

### PR DESCRIPTION
**Pull request by chidozieononiwu**
Change includes.
- Changes to the parser to allow Navigating to Definition
- Updates to UI to expand definition and scroll to appropriate definitions.
Example https://apiviewuat.azurewebsites.net/Assemblies/Review/60234aa82c8045e5b5d6951cfd04498f

### CODE REVIEW

**Comment by maririos** [comment]
Example links look good. I added @mikekistler as reviewer to get his feedback.

Not related to the PR, but is it expected to have definitions with only descriptions and no content?
image

**Comment by mikekistler** [comment]
I think this design goes a bit beyond what I was expecting. It appears that all the model definitions are replaced by links. I believe this was intended to address https://github.com/Azure/azure-sdk-tools/issues/5582, which specifically points to _nested_ models as the area of confusion. So what I was expecting was that the top-level model would be expanded as before, but then any inner models would be links to the definitions section.

Also it appears that the body parameters are still missing jump links.

image

**Comment by chidozieononiwu** [comment]
> Example links look good. I added @mikekistler as reviewer to get his feedback.
> 
> Not related to the PR, but is it expected to have definitions with only descriptions and no content? https://apiviewuat.azurewebsites.net/Assemblies/Review/60234aa82c8045e5b5d6951cfd04498f#-billingSubscription.json-Definitions-ArmErrorResponse image
``

> I think this design goes a bit beyond what I was expecting. It appears that all the model definitions are replaced by links. I believe this was intended to address #5582, which specifically points to _nested_ models as the area of confusion. So what I was expecting was that the top-level model would be expanded as before, but then any inner models would be links to the definitions section.
> 
> Also it appears that the body parameters are still missing jump links.
> 
> image

Issue #5582 requested that the model flattening be removed but instead add the properties in the definitions of the model. This just adds jumplings for each model / property that is defined in Definitions. 

I have updated this to work for Models of body parameters.

**Comment by chidozieononiwu** [comment]
> Example links look good. I added @mikekistler as reviewer to get his feedback.
> 
> Not related to the PR, but is it expected to have definitions with only descriptions and no content? https://apiviewuat.azurewebsites.net/Assemblies/Review/60234aa82c8045e5b5d6951cfd04498f#-billingSubscription.json-Definitions-ArmErrorResponse image

Those models don't have properties. They do use some a form of swagger model composition in this case ArmErrorResponse is an ErrorResponse and ArmResource is a Resource. Unfortunately we don't yet have a way to represent this in APIView.

**Comment by maririos** [comment]
> > Example links look good. I added @mikekistler as reviewer to get his feedback.
> > Not related to the PR, but is it expected to have definitions with only descriptions and no content? https://apiviewuat.azurewebsites.net/Assemblies/Review/60234aa82c8045e5b5d6951cfd04498f#-billingSubscription.json-Definitions-ArmErrorResponse image
> 
> Those models don't have properties. They do use some a form of swagger model composition in this case ArmErrorResponse is an ErrorResponse and ArmResource is a Resource. Unfortunately we don't yet have a way to represent this in APIView.

Is this something the architects want? can we file an issue for it?

**Comment by chidozieononiwu** [comment]
> > > Example links look good. I added @mikekistler as reviewer to get his feedback.
> > > Not related to the PR, but is it expected to have definitions with only descriptions and no content? https://apiviewuat.azurewebsites.net/Assemblies/Review/60234aa82c8045e5b5d6951cfd04498f#-billingSubscription.json-Definitions-ArmErrorResponse image
> > 
> > 
> > Those models don't have properties. They do use some a form of swagger model composition in this case ArmErrorResponse is an ErrorResponse and ArmResource is a Resource. Unfortunately we don't yet have a way to represent this in APIView.
> 
> Is this something the architects want? can we file an issue for it?

I have filled an issue for it https://github.com/Azure/azure-sdk-tools/issues/6487

**Review by praveenkuttappan — APPROVED** [review]

**Pull request merged**
