### PR TITLE
Switch back to smoke-test before doc publishing error gets fixed.

### PR DESCRIPTION
**Pull request by sima-zhu**

### CODE REVIEW

**Review by scbedd — APPROVED** [review]
👍 

Additional context for anyone reading this PR: The issue isn't the submission of PRs to `master`. The issue is that when CI writes to `master` (instead of `smoke-test`), there is a build failure that wasn't resolvable with information we had. Manual queues of publishing of that _same commit_ worked just fine.

**Comment by weshaggard** [comment]
Change looks good but I'm curious what our plan is to get these changes into master now? I thought we were trying to eliminate the smoke-test branch.

**Comment by sima-zhu** [comment]
> Change looks good but I'm curious what our plan is to get these changes into master now? I thought we were trying to eliminate the smoke-test branch.

@scbedd has explained in comments as well.
OPS builds triggered by master commits hide the real issue behind of SSO issue. We are not able to get the real issue before merge to live. We have a ticket filed to the docs team to resolve the issue first before we target to master.

**Comment by scbedd** [comment]
> Change looks good but I'm curious what our plan is to get these changes into master now? I thought we were trying to eliminate the smoke-test branch.

The plan is _definitely_ to eliminate the smoke-test branch. We just haven't swapped yet because when CI writes to `master`, we get a weird SSO Auth error in the build. We have an issue filed against the docs dev team, and last I heard they were actually looking at it.

**Pull request merged**
