### PR TITLE
Add new approved root namespace Azure.DigitalTwins

### PR DESCRIPTION
**Pull request by drwill-ms**

### CODE REVIEW

**Comment by pakrym** [comment]
https://azure.github.io/azure-sdk/general_design.html#namespaces doesn't seem to be updated. Is there a PR to change the guidelines?

**Comment by drwill-ms** [comment]
@pakrym not yet. in which repo does that file live?

**Comment by drwill-ms** [comment]
https://github.com/Azure/azure-sdk/pull/1320

**Comment by weshaggard** [comment]
Changes look good to but I'd like @KrzysztofCwalina to sign-off from the approved namespace prospective.

**Pull request merged**
