### PR TITLE
SwaggerAPIView upgrade to dotnet7

### PR DESCRIPTION
**Pull request by ruowan**

### CODE REVIEW

**Comment by ruowan** [comment]
@konrad-jamrozik Help to review this PR? I think I need to upgrade dotnet7

**Review by konrad-jamrozik — APPROVED** [review]
@ruowan this should just work. I am just curious: why you need to update to .NET 7?

**Comment by ruowan** [comment]
The dotnet version in global.json is 7. So to keep it consistent, we need to update the dotnet version in swagger-api-parser tools.

**Comment by konrad-jamrozik** [comment]
> The dotnet version in global.json is 7. So to keep it consistent, we need to update the dotnet version in swagger-api-parser tools.

@ruowan Just to be clear: it will also work with .NET 6. We had a long discussion about it, and a series of PRs, here:
- https://github.com/Azure/azure-sdk-tools/pull/5379

**Pull request closed without merging**
