### PR TITLE
Update Article Type for Docs.MS Doc Updates

### PR DESCRIPTION
**Pull request by scbedd**

### CODE REVIEW

**Review by danieljurek — COMMENTED** [review]
Please also update https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Update-DocsMsMetadata.ps1#L87

**Comment by scbedd** [comment]
@danieljurek  am I crazy? I did!

**Comment by danieljurek** [comment]
I meant https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/update-docs-metadata.ps1#L74

**Review by danieljurek — APPROVED** [review]

**Comment by scbedd** [comment]
The check on eng-common is taking a bit to come back. It has run successfully. 

image

Overriding check-enforcer.

**Pull request merged**
