### PR TITLE
Update `GzipUtilities` to additionally handle `brotli` encoding

### PR DESCRIPTION
**Pull request by scbedd**
Hence the rename from `GzipUtilities` to `CompressionUtilities`.

### CODE REVIEW

**Comment by benbp** [comment]
Code looks good, but is there a reason we can't farm this work out to ASP.NET middleware? e.g. https://learn.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-6.0#configuration

**Review by benbp — APPROVED** [review]

**Comment by scbedd** [comment]
> Code looks good, but is there a reason we can't farm this work out to ASP.NET middleware? e.g. https://learn.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-6.0#configuration

I could, but it would definitely mean messing with the requests when we're recording. We don't currently.

Six of one half-dozen of another. Basically.

**Pull request merged**
