### PR TITLE
Use breadcrumbfiles associated with each asset, versus shared

### PR DESCRIPTION
**Pull request by scbedd**
See title. This addresses the issues that were temporarily mitigated by [this .NET PR](https://github.com/Azure/azure-sdk-for-net/pull/37868).

### CODE REVIEW

**Review by benbp — APPROVED** [review]

**Comment by benbp** [comment]
Is this going to have any conflicts when people upgrade locally? i.e. if the new proxy ignores the existing old breadcrumb file, will it try to overwrite stuff or use different paths? I don't fully understand the "pre-breadcrumb file" behavior.

**Comment by scbedd** [comment]
> Is this going to have any conflicts when people upgrade locally? i.e. if the new proxy ignores the existing old breadcrumb file, will it try to overwrite stuff or use different paths? I don't fully understand the "pre-breadcrumb file" behavior.

It'll write new ones now. Should be seamless upgrade.

**Comment by scbedd** [comment]
/apz run tools - test-proxy - tests

**Comment by scbedd** [comment]
> > Is this going to have any conflicts when people upgrade locally? i.e. if the new proxy ignores the existing old breadcrumb file, will it try to overwrite stuff or use different paths? I don't fully understand the "pre-breadcrumb file" behavior.
> 
> It'll write new ones now. Should be seamless upgrade.

However, thinking about this over the afternoon, this upgrade will require an update of the transition script + documentation. My current plan is to 

1. Get this tested and entirely green and merged.
2. In the same PR that I bump the version of the proxy in, I'll _also_ update the migration script resources under eng/common/testproxy/transition-script/. We were also asking that I move it under `onboarding` as well. I may as well knock out all of that at the same time while I touch the script.

**Comment by scbedd** [comment]
> No commit pushedDate could be found for PR 6604 in repo Azure/azure-sdk-tools

What does this even mean devops bot!?

**Pull request merged**
