### PR TITLE
Remove defunct template

### PR DESCRIPTION
**Pull request by JimSuplizio**
docs-metadata-release.yml was replaced with common/pipelines/templates/steps/update-docsms-metadata.yml and should have been removed at that time but was not.

### CODE REVIEW

**Review by danieljurek — APPROVED** [review]

**Comment by danieljurek** [comment]
This file is ancient and not used anymore. Thanks!!

**Review by weshaggard — APPROVED** [review]

**Comment by weshaggard** [comment]
> This file is ancient and not used anymore. Thanks!!

Are there other files related that should also be cleaned up?

**Comment by danieljurek** [comment]
`update-docs-metadata.ps1` reference in this file is already removed. I think this template yml file was somehow missed in that earlier cleanup.

**Comment by JimSuplizio** [comment]
> > This file is ancient and not used anymore. Thanks!!
> 
> Are there other files related that should also be cleaned up?

Only the template yml file needs to be removed. The script the template was using, update-docs-metadata.ps1, was already removed.

**Pull request merged**
