### PR TITLE
Set .NET used by our tools to `net6.0` + minor updates to .sln files

### PR DESCRIPTION
**Pull request by konrad-jamrozik**
This PR addresses issues #4934 and #4935 for the following tools and other projects, by migrating their target frameworks to `net6.0`, and ensuring that their `ci.yml` sets `DotNetCoreVersion: 6.0.403`:
- `version-guard`;
- `CreateRuleFabricBot` and its tests;
- `code-owners-parser` and its tests. This required disabling execution of `get-codeowners.ps1` script as part of the test suite. Follow-up work to re-enable it: #4938;
- `notification-configuration`;
- `identity-resolution`;
- `generator` (i.e. `Stress.Generator`) and its tests;
- `Azure.ClientSdk.Analyzers` and its tests;
- `SwaggerApiParser`. This only required setting `ci.yml` to point to .NET 6, as it was already targeting `net6.0`;
- `snippet-generator` and its tests;
- `tools\agent-time-extractor\AgentTimeExtractor\AgentTimeExtractor.csproj`;
- `src\dotnet\APIView\TestLibrary\TestLibrary.csproj`, which was using `netcoreapp2.1` which is out of support since [August 2021](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core), but [the APIView pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1136&_a=summary) and the pipeline seems to be failing due to unrelated reasons, so usage of `netcoreapp2.1` seems to be non-blocking. Nevertheless, I updated it to `net6.0` anyway;
- `Azure.Sdk.Tools.HttpFaultInjector`;
- `Azure.Sdk.Tools.HttpFaultInjector.StorageBlobsSample`;
- `Azure.Sdk.Tools.HttpFaultInjector.HttpClientSample`;
- Sample projects of `TestProxy`, but not the `TestProxy` itself, as it was already on `net6.0`, albeit it also targets `net5.0`, which I left unchanged;
- `PixelServer`, which required adding an import to `Program.cs`. Note I couldn't find a corresponding `ci.yml` or pipeline for it.

## Tools not updated to `net6.0` in this PR

`<TargetFramework>` occurrences **not** migrated as part of this PR, and why:

- Any tools targetting `netstandard` as [it is compatible with .NET 6.0](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1);
- `tools\pipeline-generator\Azure.Sdk.Tools.PipelineGenerator\Azure.Sdk.Tools.PipelineGenerator.csproj`, because it is done in PR #4915 
- `tools\check-enforcer\Azure.Sdk.Tools.CheckEnforcer\Azure.Sdk.Tools.CheckEnforcer.csproj`, as it uses `archetype-sdk-tool-azure-function.yml` archetype, which doesn't support the `DotNetCoreVersion` override. `CheckEnforcer` currently targets `netcoreapp3.1`;
- `tools\github-issues\Azure.Sdk.Tools.GitHubIssues\Azure.Sdk.Tools.GitHubIssues.csproj`, for the same reason as `check-enforcer`. `GitHubIssues` currently targets `netcoreapp3.1`.
- `tools\webhook-router\Azure.Sdk.Tools.WebhookRouter\Azure.Sdk.Tools.WebhookRouter.csproj`, for the same reasons as `check-enforcer`. `WebhookRouter` currently target `netcoreapp3.1`.

## Additional remarks

Another PR addressing the same two issues, but by for the tool `PipelineGenerator`, is #4915.

As a secondary mini-refactoring, this PR also adds `ci.yml` files to corresponding `.sln` or `.csproj` files and updates the `.sln` files Visual Studio version used to VS 2022. Note I was inconsistent in adding the `ci.yml` files to `.csl` vs `.csproj`, but I will fix it in future PR, as this PR is time-sensitive per #4934.

### CODE REVIEW

**Review by benbp — APPROVED** [review]
+1 thank you for doing this! For check-enforcer and possibly webhook router, we can start to delete those projects entirely, I think. @hallipr just to double check, nothing of yours relies on the webhook-router eventhubs, right?

**Comment by konrad-jamrozik** [comment]
@benbp If so, I will make a separate PR to delete these projects.

@weshaggard I am merging, assuming Ben's approval is enough. Let me know in case that's incorrect assumption xD

**Review by weshaggard — COMMENTED** [review]
LGTM

**Comment by konrad-jamrozik** [comment]
@benbp @hallipr created PRs to delete the two obsolete projects:
- #4963 
- #4966

**Pull request merged**
