### PR TITLE
`/.azure-pipelines/warden.yml` → `/eng/pipelines/doc-warden.yml`

### PR DESCRIPTION
**Pull request by konrad-jamrozik**
Contributes to:

- #5056

Once this PR is merged, I will update the relevant pipeline to point to the new location of its definition file:  
https://dev.azure.com/azure-sdk/internal/_build?definitionId=106

### CODE REVIEW

**Comment by konrad-jamrozik** [comment]
@weshaggard [the warden pipeline](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=106) has all its triggers disabled via ADO UI and last run was in Dec 9, 2021, over 14 months ago. There also doesn't seem to be much activity in the [packages/python-packages/doc-warden](https://github.com/Azure/azure-sdk-tools/tree/main/packages/python-packages/doc-warden).

@scbedd @heaths @chidozieononiwu do you folks know if doc warden is still in use? If yes, why nobody is running the pipeline anymore? Can it be deleted?

**Comment by heaths** [comment]
I didn't realize it wasn't running, but I don't know why it was turned off. I know it found some valid issues.

**Review by weshaggard — APPROVED** [review]
Looks good. Be sure to update the pipeline to point to the new location.

**Comment by weshaggard** [comment]
@konrad-jamrozik it is still in use for most of our language repos today. We have plans to retire it and move to a more generic MD linter tool in the future but that work is still on the backlog. See https://github.com/Azure/azure-sdk-tools/issues/1896

**Comment by konrad-jamrozik** [comment]
PR merged & I have updated the pipeline.

**Pull request merged**
