### PR TITLE
Feature/swagger parser upgrade

### PR DESCRIPTION
**Pull request by chidozieononiwu**
- Resolves
https://github.com/Azure/azure-sdk-tools/issues/5582
https://github.com/Azure/azure-sdk-tools/issues/6008
https://github.com/Azure/azure-sdk-tools/issues/6188
https://github.com/Azure/azure-sdk-tools/issues/6259
https://github.com/Azure/azure-sdk-tools/issues/4978
https://github.com/Azure/azure-sdk-tools/issues/6296

|Before Upgrade|After Upgrade|
|-------|-----|
|[communicationservicejobrouter - before](https://apiviewstaging.azurewebsites.net/Assemblies/Review/15f87bfa13a1481abb51dec83bafb331)|[communicationservicejobrouter - after](https://apiviewstaging.azurewebsites.net/Assemblies/Review/6c147de0a3454bcdb4ba31bf5c4f07db)|
|[elevation - before](https://apiviewstaging.azurewebsites.net/Assemblies/Review/5e7968881fc4489e8113715b2c475a9a)|[elevation - after](https://apiviewstaging.azurewebsites.net/Assemblies/Review/3f7e6a8b637c4b4588040a97c1ff9a86)|
|[communicationservicessiprouting - before](https://apiviewstaging.azurewebsites.net/Assemblies/Review/9713f5611c754d728619e13c649d5c27)|[communicationservicessiprouting - after](https://apiviewstaging.azurewebsites.net/Assemblies/Review/7ef2e56551f94b8ca9432ea970a05ac5)|

### CODE REVIEW

**Comment by heaths** [comment]
I'm afraid I don't have a lot of familiarity with this to really approve, though I'm happy to take a look conceptually.

With some of the changes I see, though, I want to make sure: are properties of models still listed breadth-first - which I fixed in #5802 - instead of depth-first like they were?

**Comment by chidozieononiwu** [comment]
> I'm afraid I don't have a lot of familiarity with this to really approve, though I'm happy to take a look conceptually.
> 
> With some of the changes I see, though, I want to make sure: are properties of models still listed breadth-first - which I fixed in #5802 - instead of depth-first like they were?

Based on request in https://github.com/Azure/azure-sdk-tools/issues/5582 I removed the nesting of models, instead I add each model to the definition where the properties are listed for each model.

**Comment by heaths** [comment]
> > I'm afraid I don't have a lot of familiarity with this to really approve, though I'm happy to take a look conceptually.
> > With some of the changes I see, though, I want to make sure: are properties of models still listed breadth-first - which I fixed in #5802 - instead of depth-first like they were?
> 
> Based on request in #5582 I removed the nesting of models, instead I add each model to the definition where the properties are listed for each model.

Is there a preview?

**Comment by maririos** [comment]
>Is there a preview?

@heaths description was updated to show the differences

**Comment by maririos** [comment]
@mikekistler coudl you also take a look at this PR?

**Comment by mikekistler** [comment]
I thought the plan for fixing the confusing flattening of models #5582 was to link to the model definition rather than expanding it in the request or response body section.  But the the preview above there are no links:

image

**Comment by mikekistler** [comment]
@chidozieononiwu Could you post a list of the improvements here -- a brief summary is fine, something like what we would post in the change log and advertise to the team.

**Comment by chidozieononiwu** [comment]
> I thought the plan for fixing the confusing flattening of models #5582 was to link to the model definition rather than expanding it in the request or response body section. But the the preview above there are no links:
> 
> image

You are right. The actual linking will need to be a UI change yet to be made.

**Review by praveenkuttappan — APPROVED** [review]
looks good.

**Pull request merged**
