### PR TITLE
Update docindex.yml to use Python 3.11

### PR DESCRIPTION
**Pull request by danieljurek**

### CODE REVIEW

**Comment by danieljurek** [comment]
Successful docindex runs: 

* c https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4317647&view=logs&j=5e8cddd4-765d-5046-f31f-2d7d6b215293&t=af0bdecc-8eb1-5abc-29ea-2230863efa8c
* cpp https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4317648&view=results
* java https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4317649&view=results
* js https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4317650&view=results -- There is a failure in an unrelated job. The failure will be addressed separately. 
* net https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4317651&view=results
* python https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4317652&view=results

**Review by weshaggard — APPROVED** [review]

**Review by benbp — APPROVED** [review]

**Comment by danieljurek** [comment]
check-enforcer may be waiting for other pipelines. No such other pipelines will run directly against this PR. Overriding.

**Pull request merged**
