### PR TITLE
Bump test proxy version

### PR DESCRIPTION
**Pull request by billwert**
Includes:

- #6517
- #6484
- #6564
- #6604

### CODE REVIEW

**Review by scbedd — APPROVED** [review]
Approving. Sync PRs are creating now. We just need to ensure that we don't have any unexpected reds on those sync PRs.

**Review by scbedd — CHANGES_REQUESTED** [review]
Withdrawing approval, `.NET` tests turned up some hard breaking changes.

**Review by benbp — COMMENTED** [review]
Revoking approval, accident

**Review by scbedd — APPROVED** [review]
Now I need to tackle the broken links from this, but it's g2g.

**Pull request merged**
