### PR TITLE
Add swagger for Test-Proxy

### PR DESCRIPTION
**Pull request by JoshLove-msft**

### CODE REVIEW

**Review by HarshaNalluru — APPROVED** [review]

**Comment by weshaggard** [comment]
This is cool to see but for my information was there a particular issue/scenario that we added this for? I'm mostly curious because I want to understand what our maintenance story is going to be for this to ensure it stays updated.

**Comment by benbp** [comment]
@weshaggard @JoshLove-msft agreed if this was auto-generated then we should add corresponding docs and/or CI to keep it fresh. Also, it may be a good idea to host a swagger endpoint from the test proxy, if it's not done already?

**Comment by JoshLove-msft** [comment]
> This is cool to see but for my information was there a particular issue/scenario that we added this for? I'm mostly curious because I want to understand what our maintenance story is going to be for this to ensure it stays updated.

This was added here so that other languages could use it for generating the code needed to perform operations with the proxy server. I don't think we have a defined strategy for keeping it up to date. Typically, the way it would work is that when new operations are added to the Test-Proxy, the swagger would be updated to include them.

> @weshaggard @JoshLove-msft agreed if this was auto-generated then we should add corresponding docs and/or CI to keep it fresh. Also, it may be a good idea to host a swagger endpoint from the test proxy, if it's not done already?

This was not auto-generated. It was written based on the available operations in the test proxy.

**Comment by HarshaNalluru** [comment]
At the moment, only .NET uses it.
I'm planning to leverage this in JS too.

**Comment by benbp** [comment]
> This was not auto-generated. It was written based on the available operations in the test proxy.

Ah ok. Well in that case I think it's ideal if we can move towards having this be auto-generated. It seems like the API surface area is rather small so I don't think this would be a huge amount of work? @scbedd?

**Comment by JoshLove-msft** [comment]
> > This was not auto-generated. It was written based on the available operations in the test proxy.
> 
> Ah ok. Well in that case I think it's ideal if we can move towards having this be auto-generated. It seems like the API surface area is rather small so I don't think this would be a huge amount of work? @scbedd?

If we can figure out how to do that - then I'll bet the folks working on code gen would be interested as well. AFAIK swaggers are written by hand based on the service specs.

**Comment by JoshLove-msft** [comment]
Talked to @benbp - I didn't realize that there was tooling that would do this automatically for ASP.NET - https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0&tabs=visual-studio

**Pull request merged**
