### PR TITLE
Release `typespec-apiview` 

### PR DESCRIPTION
**Pull request by tjprescott**
Renames `cadl-apiview` to `typespec-apiview`.

### CODE REVIEW

**Review by konrad-jamrozik — APPROVED** [review]

**Comment by tjprescott** [comment]
@praveenkuttappan @chidozieononiwu any ideas why this is not running the CI pipeline? The tests all pass when run locally. :thinking:

**Comment by tjprescott** [comment]
That is correct. This is only compatible with `@typespec/compiler 0.41`

**Pull request merged**
