### PR TITLE
APIView add rerun pipeline if failure

### PR DESCRIPTION
**Pull request by maririos**

### CODE REVIEW

**Comment by maririos** [comment]
@praveenkuttappan I think this is the right place 😕

**Review by praveenkuttappan — APPROVED** [review]

**Comment by praveenkuttappan** [comment]
> @praveenkuttappan I think this is the right place 😕

This information is added to ADO work item and displayed in release planner.

**Comment by weshaggard** [comment]
@maririos it doesn't look like you followed the workflow to get this change merged in all the other repos. I just approved the sync PR step in your PR https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4338326&view=logs&j=33796ffc-d0c5-548c-0c1d-9d1ddb84594a please follow-up and approve those PRs and get the merged.

**Comment by weshaggard** [comment]
@maririos I finished the syncing process.

**Comment by maririos** [comment]
> @maririos I finished the syncing process.

Thank you again

**Pull request merged**
