### PR TITLE
Allow matrix replace queries to work for overriding parameter group display names

### PR DESCRIPTION
**Pull request by benbp**
Currently, if a matrix replace query changes the values found within a parameter grouping, we don't make any modifications to the display name of that grouping. There's no way for us to know what that name should be changed to, so the parameter grouping display name is an intended behavior to prevent names from becoming unreadably long if inner parameter values are displayed. For example:

```
  "matrix": {
    "Agent": {
      "ubuntu-18.04": {
          "OSVmImage": "MMSUbuntu18.04",
          "Pool": "azsdk-pool-mms-ubuntu-1804-general"
      }
  }
```

The display name for this matrix entry will be `ubuntu_1804` as opposed to `MMSUbuntu1804_azsdkpoolmmsubuntu1804general`. One case where this is useful is for custom storage pools, where the only value we change in the above config is replacing the substring `-general` with `-storage`, but we still want to preserve the job display names for readability and consistency with other pipelines.

However, this approach cause some problems where, for whatever reason, the parameters in the grouping are changed such that the display name becomes misleading.

For example, we recently performed a temporary override of ALL macos CI pipeline jobs to use ubuntu instead ([PR](https://github.com/Azure/azure-sdk-for-js/pull/14785)), due to capacity issues. Using `replace` was the easiest way to do this without having to change all the matrix configs, and to preserve the original agent configuration for live tests. This has the effect, however, of changing the images to ubuntu, while the job display name still includes "macos".

In order to provide a compromise here, we will still preserve the display name in normal cases of replacing parameters, but we will make the parameter group display name ALSO be queryable by `replace`, which you can use in combination with parameter name/value replacements for more control. So for the above code snippet, a query like `-replace @("Agent=ubuntu-18.04/replacedGroupingName", "OSVmImage=MMSUbuntu.*/replacedParameter")` will change the display name to `replacedGroupingName` which should describe the updated matrix parameter `OSVmImage`.

I'm hesitant to provide a README update for this, because it's very niche and takes a lot to explain. I worry it will make the docs more confusing and I'm not sure we want many people using this feature anyways.

### CODE REVIEW

**Comment by mitchdenny** [comment]
This seems pretty complex to me. I'm wondering whether in this particular case we would have been better just disabling the macOS tests entirely whilst there was an availability issue. Am I missing something?

**Comment by weshaggard** [comment]
While I'm not opposed to the flexibility this might have I do wonder if adding it for the macos case is worth the extra complexity.

Lets chat next week I have some ideas of how we might be able to handle replacing and/or removing of these type of things globally which might not require us to need to commit changes to all the repo's like we did in this case.

**Comment by benbp** [comment]
@mitchdenny @weshaggard totally agree with both your comments and I'm not sure I think this should be merged.

Re: disabling macos entirely, the issue with this approach was that we would have lost coverage of specific versions and parameters that are covered by macos in the sparse matrix. So the alternative would have been to make direct changes to all the matrix files, which @mikeharder and I were reluctant to do for the short term mitigation (it being a larger change).

Re: disabling globally, yes let's have that chat. I think having these sorts of "global config backdoors" is going to give us a lot of needed control to react to situations like this.

**Comment by benbp** [comment]
Closing in favor of exploring other solutions to the macos capacity issue that obviates the need for this workaround.

**Pull request closed without merging**
