### PR TITLE
Properly handle when `git` encounters an unrecoverable error

### LINKED ISSUE #9208: Address infinite loop in `gitprocessexception` while invoking `push`
@skadhiresan reported a very interesting issue where the `test-proxy` entered an infinite loop of retrying the `git push` command before erroring. Looking something like **[1]**.

On running the failing `push` command with `debug` mode enabled, the issue became apparent:

```powershell
PS C:\Users\skadhiresan\source\repos\azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources> test-proxy push -a ./assets.json
Running proxy version is Azure.Sdk.Tools.TestProxy 20240919.1
git --version
StdOut: git version 2.47.0.windows.1
 
StdErr:
ExitCode: 0
git remote -v
StdOut: origin  https://github.com/skadhiresan/azure-sdk-for-net.git (fetch)
origin  https://github.com/skadhiresan/azure-sdk-for-net.git (push)
 
StdErr:
ExitCode: 0
git remote set-url origin https://github.com/Azure/azure-sdk-assets
StdOut:
StdErr: fatal: detected dubious ownership in repository at 'C:/Users/skadhiresan/source/repos/azure-sdk-for-net/.assets/sztCmI9VWt'
'C:/Users/skadhiresan/source/repos/azure-sdk-for-net/.assets/sztCmI9VWt' is owned by:
        BUILTIN/Administrators (S-1-5-32-544)
but the current user is:
        REDMOND/skadhiresan (S-1-12-1-2625456001-1339269914-2951898773-3550298200)
To add an exception for this directory, call:
 
        git config --global --add safe.directory C:/Users/skadhiresan/source/repos/azure-sdk-for-net/.assets/sztCmI9VWt
 
ExitCode: 128
Exception of type 'Azure.Sdk.Tools.TestProxy.Common.Exceptions.GitProcessException' was thrown.
Unhandled exception:
PS C:\Users\skadhiresan\source\repos\azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources>
```

We checked that this issue disappeared if we ran the `test-proxy push` from the same elevated command prompt. It worked flawlesslyl. This proves to me that it's a permissions issue. The **real** problem is that the proxy is hiding these file permissions error behind a wall of  exception output.

This issue covers addressing the infinite loop so that the exception can dump out immediately.

**[1]**
Image
Image

### PR DESCRIPTION
**Pull request by scbedd**
Don't infinitely loop. Resolves #9208

### CODE REVIEW

**Review by benbp — APPROVED** [review]

**Comment by scbedd** [comment]
As much as I hate to admit it, I don't think this is the right solution. The `Environment.Exit` is wrong. The source of the unhandled exception is because we're running in two different "modes" in the proxy.

1. On CLI invocation of `restore` or `push`, we want to report a `git` error to CLI, then early exit from whatever command we're invoking.
2. When the proxy is running in a server, we want to throw a `GitProcessException` (which is an `HttpException`) because our custom ASP.NET middleware will turn that unhandled exception into a clean HTTP response for the user.

Effectively, my solution will cause the server to _straight crash_ if anything goes wrong with any "unhandled" `git` exception.

**Comment by scbedd** [comment]
> As much as I hate to admit it, I don't think this is the right solution. The `Environment.Exit` is wrong. The source of the unhandled exception is because we're running in two different "modes" in the proxy.
> 
> 1. On CLI invocation of `restore` or `push`, we want to report a `git` error to CLI, then early exit from whatever command we're invoking.
> 2. When the proxy is running in a server, we want to throw a `GitProcessException` (which is an `HttpException`) because our custom ASP.NET middleware will turn that unhandled exception into a clean HTTP response for the user.
> 
> Effectively, my solution will cause the server to _straight crash_ if anything goes wrong with any "unhandled" `git` exception. I'm going to refactor so we can _know_ what mode we're in via function signature update.

Added a bit for this exact binary setting to `GitProcessHandler`, and honor it. That addresses the above without entirely rewriting every usage of `GitHandler.Run`.

**Pull request merged**
