### PR TITLE
Add create review help link for python

### PR DESCRIPTION
**Pull request by praveenkuttappan**
Show helper text for python in Create new review window.

### CODE REVIEW

**Comment by praveenkuttappan** [comment]
create_review

**Comment by praveenkuttappan** [comment]
@annatisch, @kristapratico  : Just fyi. new help text in create review.

**Comment by pakrym** [comment]
I though we've built generator support into APIView itself, why are we telling people to upload json files?

**Comment by praveenkuttappan** [comment]
@pakrym : Python team preferred this approach to generate from source instead of uploading package to have more insights about the code and linting. Tool does support uploading whl package as well though I still need few more tweaks in it.

**Comment by pakrym** [comment]
This approach doesn't have a benefit of being able to re-generate listing after generator changes. We should unify on one.

**Pull request merged**
