### PR TITLE
Test .NET changes in multiple OSes

### LINKED ISSUE #5159: Build dotnet tools with matrix of OSes
We should build src/dotnet tools with different OSes like we do in the Azure/azure-sdk-for-net directory to make sure all our tests work across OSes and any TFMs we might add e.g., `net472` on Windows.

See https://github.com/Azure/azure-sdk-tools/pull/5154#discussion_r1073098588 by @heaths for context.

### PR DESCRIPTION
**Pull request by heaths**
Resolves #5159

### CODE REVIEW

**Review by konrad-jamrozik — APPROVED** [review]

**Comment by heaths** [comment]
Pipeline test passed, so overriding checkenforcer.

**Comment by weshaggard** [comment]
@heaths can you link to the pipeline test? It would have been good to run a couple of them to make sure this doesn't break them.

**Comment by heaths** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2129392

**Pull request merged**
