### PR TITLE
[Python APIView] Move pylintrc into the apistub folder and include in the WHL

### PR DESCRIPTION
**Pull request by tjprescott**
Fixes a packaging issue with api-stub-generator 0.3.0 because pylintrc is not included.

### CODE REVIEW

**Comment by scbedd** [comment]
@tjprescott I think you will need to include a `package_data` argument to your setup.py so that it gets included in your wheel as well. (And set flat `include_package_data`)

**Comment by tjprescott** [comment]
> @tjprescott I think you will need to include a package_data argument to your setup.py so that it gets included in your wheel as well. (And set flag include_package_data)

Yeah, I had that and it still failed. Then I saw it said to include the file in the MANIFEST and that failed too. Now I will try having both simultaneously. 😆

**Comment by tjprescott** [comment]
Oh hey it worked! @scbedd please review before it turns red!

**Review by scbedd — APPROVED** [review]
Yeah!

Good rule of thumb: `MANIFEST.in` -> what's in SDIST
`setup.py` -> what's in wheel.

It's not a HUNDRED percent true in all cases, but that's how I think about it.

**Pull request merged**
