### PR TITLE
Do not print red success message

### PR DESCRIPTION
**Pull request by heaths**
Resolves Azure/azure-sdk-for-net#22347 and is a port of Azure/azure-sdk-for-net#23210

### CODE REVIEW

**Comment by heaths** [comment]
Seems there's no PR or CI for the tools/ directory and probably should be, to at least make sure things build and can be packaged as needed.

/cc @chidozieononiwu @weshaggard

**Comment by heaths** [comment]
Hmm, also doesn't seem to be any require reviews.

**Comment by weshaggard** [comment]
@chidozieononiwu what is the status of moving this tool? I know that you closed out your PR that used but I'm not sure if that was just temporary or not.

As for required reviewers I just fixed that. And for the pipeline I think @chidozieononiwu set one up for this tool but I'm not sure of its current state.

**Comment by chidozieononiwu** [comment]
> @chidozieononiwu what is the status of moving this tool? I know that you closed out your PR that used but I'm not sure if that was just temporary or not.
> 
> As for required reviewers I just fixed that. And for the pipeline I think @chidozieononiwu set one up for this tool but I'm not sure of its current state.

Its open again https://github.com/Azure/azure-sdk-for-net/pull/22783

**Comment by heaths** [comment]
Since this PR is a port, can we get this one merged as well so when the package is deployed we get consistent behavior?

**Pull request merged**
