### PR TITLE
Prevent sidebar from jumping

### PR DESCRIPTION
**Pull request by JoshLove-msft**

### CODE REVIEW

**Comment by pakrym** [comment]
What changed?

**Comment by JoshLove-msft** [comment]
> What changed?

I changed something in the sticky-sidebar.js file.

**Comment by JoshLove-msft** [comment]
> > What changed?
> 
> I changed something in the sticky-sidebar.js file.

Actually, looks like it still isn't working..

**Comment by pakrym** [comment]
https://github.com/abouolia/sticky-sidebar/issues/44#issuecomment-348788166

**Comment by JoshLove-msft** [comment]
> [abouolia/sticky-sidebar#44 (comment)](https://github.com/abouolia/sticky-sidebar/issues/44#issuecomment-348788166)

That seems to have fixed it. Thanks for finding that!

**Pull request merged**
