### PR TITLE
add annotatin declaration support

### PR DESCRIPTION
**Pull request by mssfang**
fixes: #648

### CODE REVIEW

**Comment by JonathanGiles** [comment]
Can you post an apiview with this fix applied?

**Comment by mssfang** [comment]
https://apiview.dev/Assemblies/Review/8520e97afd3045e2942f5d9b7a6a77b3#com.azure.search.documents.indexes.FieldIgnore

**Comment by JonathanGiles** [comment]
You missed a version update in the c# code

**Comment by mssfang** [comment]
how about now?

**Comment by JonathanGiles** [comment]
// cc @pakrym for a new release of APIView when time allows. Thanks.

**Comment by pakrym** [comment]
I'm out tomorrow but @mssfang and @praveenkuttappan have access to deployment approval for the site.

**Pull request merged**
