### PR TITLE
Add Kusto function definition of SpecsPipelinesBuildsJobLogs.kql

### PR DESCRIPTION
**Pull request by konrad-jamrozik**
See the comment in the added function for details.

I followed the guidance I wrote down earlier here:
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/625/Kusto-Query-Catalog?anchor=adding-functions-to-%60azsdkengsys%60-cluster

### CODE REVIEW

**Review by weshaggard — APPROVED** [review]
I assume you are just backing up this here which is fine

**Comment by konrad-jamrozik** [comment]
> I assume you are just backing up this here which is fine

Exactly!

**Pull request merged**
