### PR TITLE
Fix notification subscriber

### PR DESCRIPTION
**Pull request by danieljurek**

### CODE REVIEW

**Review by weshaggard — APPROVED** [review]
The changes look good overall. Lets just try and validate the one case pointed out and then get this merged.

**Review by weshaggard — CHANGES_REQUESTED** [review]
On further inspection we need to fix this in the github-codeowner-subscriber library as well.

**Comment by weshaggard** [comment]
https://github.com/Azure/azure-sdk-tools/blob/master/tools/notification-configuration/github-codeowner-subscriber/Program.cs#L75

That needs to also use your new paging function. Time to move it into common.

**Comment by danieljurek** [comment]
Not sure how I accidentally closed this one

**Comment by danieljurek** [comment]
Now I see why this PR was closed. It looks like force-pushing a rebase caught the branch up to the fact that these changes have already merged in another pr -- https://github.com/Azure/azure-sdk-tools/pull/1339/files ... So these changes did go in! 

This is a slightly separate issue with a rather similar root cause.

**Comment by danieljurek** [comment]
New PR opened to address this: https://github.com/Azure/azure-sdk-tools/pull/1544

**Pull request closed without merging**
