### PR TITLE
Add azure-sdk-for-rust to utility pipelines

### PR DESCRIPTION
**Pull request by hallipr**

### CODE REVIEW

**Review by weshaggard — CHANGES_REQUESTED** [review]
Lets hold on this until the eng\common changes hit the main branch in the rust repo.

**Review by heaths — APPROVED** [review]

**Review by RickWinter — APPROVED** [review]
@weshaggard Do you still have requested changes?

**Comment by weshaggard** [comment]
@hallipr please add rust to https://github.com/Azure/azure-sdk-tools/blob/main/eng/pipelines/eng-workflows-sync.yml as well so the workflows sync also. After this PR gets merged then do a sync.

**Review by weshaggard — APPROVED** [review]
please add to workflow sync too.

**Pull request merged**
