### PR TITLE
[sdk-testgen] add armTemplatePayloadString in testmodeler

### PR DESCRIPTION
**Pull request by changlong-liu**
the field is designed for .Net test generation

### CODE REVIEW

**Review by tadelesh — COMMENTED** [review]
I don't think it is a good way to add a duplicated json string to the testmodeler.

**Comment by changlong-liu** [comment]
> I don't think it is a good way to add a duplicated json string to the testmodeler. A good practice may be convert it at language testgen or generate it directly with language specific type.

Hi @ArcturusZhang , @tadelesh, @lirenhe ,  Shall we discuss whether armtemplate jsonstring should added to testmodeler?

I think we can add a on/off flag on this? Since it 1) make .Net testGen easier and 2) don't affect other languages if don't need this.

**Comment by tadelesh** [comment]
When there exists variables in arm template's `environmentVariables` or `arguments`, will the variable replacement happen in json string? Will it be hard to do so?

**Pull request merged**
