### PR TITLE
When installing dev package, target a specific index

### PR DESCRIPTION
**Pull request by scbedd**
@praveenkuttappan @tjprescott I am pretty certain this will be fine for our runs.

Does this same concern affect how we currently install the api-stub-generator during APIView deploy?

### CODE REVIEW

**Comment by tjprescott** [comment]
@scbedd I think targeting a specific index makes sense, but shouldn't it be here, not the SDK? Didn't you move the pylint-guidelines-checker to this repo?

**Comment by scbedd** [comment]
I see. We want to make this a dev install. Done.

**Comment by scbedd** [comment]
@tjprescott No I think this is right.

This `api-stub-generator` is what gets used to create APIReviews right? And it uses the `pylint-guidelines-checker` to generate part of it's failures.

In the pipeline checking this api stub generator, do we want to use the version being developed or the same one as what APIView uses?

**Comment by tjprescott** [comment]
@scbedd we should what APIView uses so this looks like the right approach. Thank you!

**Review by tjprescott — APPROVED** [review]

**Review by weshaggard — APPROVED** [review]

**Comment by scbedd** [comment]
This PR will fail until [this other PR](https://github.com/Azure/azure-sdk-tools/pull/3252) is invoked for the dependent packages.

**Pull request merged**
