### PR TITLE
Convert pipeline to run under 1ES template

### PR DESCRIPTION
**Pull request by weshaggard**

### CODE REVIEW

**Review by benbp — APPROVED** [review]

**Review by benbp — APPROVED** [review]

**Comment by weshaggard** [comment]
failures are known issues (publishing an already published version and a bug in the 1ES templates around tagging) but I've verified that the pipelines function outside of those issues.

**Comment by weshaggard** [comment]
@microsoft-github-policy-service rerun

**Comment by weshaggard** [comment]
@microsoft-github-policy-service rerun

**Pull request merged**
