### PR TITLE
[Python APIView] Support TypedDict

### LINKED ISSUE #2568: [Python APIView] TypedDict classes not supported
```Python
FooProperties = TypedDict(
    'FooProperties',
    id=str
)
```

Renders as:
```Python
class FooProperties(dict):
```

### PR DESCRIPTION
**Pull request by tjprescott**
Fix #2568.

https://apiviewstaging.azurewebsites.net/Assemblies/Review/5e455e3a04cc4a25b5926a602cd98da3/231d2bb07ce7417f835164d39d7ce9fd?diffRevisionId=114158e62a5248f6b86c6048897609e9&doc=False&diffOnly=False

### CODE REVIEW

**Comment by tjprescott** [comment]
@annatisch what syntax would you suggest for displaying this?

**Current**
```python
class MyTypedDict(dict):
   property name: str
   property age: int
```

**Alternative**
```python
class MyTypedDict(dict):
   key "name": str
   key "age": int
```

Or something different?

**Comment by annatisch** [comment]
Thanks @tjprescott, I think I prefer the formatting of the latter.
Do you think we need any other kind of visual hint that this was declared as a `TypedDict`? Or just the fact that the keys have type hints is enough?

**Comment by tjprescott** [comment]
The type information that Python yields through inspect just says `dict`, but we could probably force it to say `TypedDict` like it does in the code.

**Comment by tjprescott** [comment]
@annatisch here's the updated syntax:
image

**Comment by annatisch** [comment]
Thanks @tjprescott - I think it looks great :)

**Review by annatisch — APPROVED** [review]
LGTM :)

**Pull request merged**
