### PR TITLE
[FabricBot] Remove Rule Generator

### PR DESCRIPTION
**Pull request by jsquire**
# Summary

The focus of these changes is to remove the legacy tool that was once used to generate Fabric Bot rules from the code owners files for a repository.  This tool has been broken for a couple of years and worked only with the retired FabricBot service API.

Now that FabricBot has been retired, there is no need for retaining this tool.

### CODE REVIEW

**Review by weshaggard — APPROVED** [review]

**Comment by weshaggard** [comment]
We should also delete any associated pipeline once this gets merged.

**Comment by jsquire** [comment]
Good call, @weshaggard.    I didn't realize there was one;  pipeline `tools - ConfigureFabricBot` has been deleted.

**Comment by konrad-jamrozik** [comment]
Just for reference, this is a follow-up to my previous attempt:
- https://github.com/Azure/azure-sdk-tools/pull/4974

**Comment by jsquire** [comment]
Apologies, @konrad-jamrozik.   I totally forgot that was a thing!

**Comment by konrad-jamrozik** [comment]
@jsquire no worries! ;)

**Pull request merged**
