### PR TITLE
Invalid use of @overload v2

### PR DESCRIPTION
**Pull request by 16234397**
Updated pull request from closed request https://github.com/Azure/azure-sdk-tools/pull/9014

### CODE REVIEW

**Review by l0lawrence — APPROVED** [review]
lgtm!

**Comment by 16234397** [comment]
> lgtm!

**Comment by 16234397** [comment]
> lgtm!

Cool, I just got rid of the merge conflicts again :-)

**Comment by 16234397** [comment]
@l0lawrence merge conflicts removed again, let me know if you want anything else done.

**Pull request merged**
