### PR TITLE
Combine approval indicator and request approval button

### PR DESCRIPTION
**Pull request by chidozieononiwu**
Old
Approval Separate
New
Approval Combined
Approval Combined Pending
Approval Combined Dropdown

### CODE REVIEW

**Comment by JonathanGiles** [comment]
I'm a little confused what the new buttons do - can you demonstrate or explain how they are used?

**Comment by chidozieononiwu** [comment]
> I'm a little confused what the new buttons do - can you demonstrate or explain how they are used?

Am just combining the approval status indicator and the request approval dropdown into one button group.
We still get the dropdown for requesting approval, the green check to show the review is approved and the popover that show the approvers. I have also added a green border around the review panels for approved reviews.
Approval Combined Dropdown
Approval Combined Pending
Approval Combined
ApprovedReviewPanel

**Comment by JonathanGiles** [comment]
Got it - so the 'approve' button remains separate still - that's what confused me.

**Review by JonathanGiles — APPROVED** [review]

**Comment by chidozieononiwu** [comment]
> Got it - so the 'approve' button remains separate still - that's what confused me.

Yes that is still separate since it only show up for people who can approve.

**Pull request merged**
