### PR TITLE
Fix logging message in secret tool

### PR DESCRIPTION
**Pull request by weshaggard**

### CODE REVIEW

**Comment by weshaggard** [comment]
@benbp looks like you missed updating the public ci pipeline after the rename. I fixed it.

**Comment by weshaggard** [comment]
Well I renamed it the pipeline is still broken because of the strong name issue.

**Comment by benbp** [comment]
> @benbp looks like you missed updating the public ci pipeline after the rename. I fixed it.

Ah good catch, thanks. I only saw the internal one.

**Comment by benbp** [comment]
> Well I renamed it the pipeline is still broken because of the strong name issue.

If we merge in https://github.com/Azure/azure-sdk-tools/pull/6048 it would probably fix the public pipeline at least?

**Comment by weshaggard** [comment]
Fixed in https://github.com/Azure/azure-sdk-tools/pull/6095

**Pull request closed without merging**
