### PR TITLE
Check Enforcer timeout handling (WIP)

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR adds support for timeout behaviors in Check Enforcer. The way it works is that Check Enforcer will fire a function at a regular interval and read a list of pull requests that it has seen recently from Azure Storage (tables). It will then query that pull request to determine whether it has any check-runs, and if it doesn't, and add a comment with the contents of a markdown file from the source repository.

This will require a modification to the existing ```CHECKENFORCER``` configuration file to specify the timeout period. The markdown file will be discovered by convention ... ```CHECKENFORCER-TIMEOUT.md```.

Protections will need to be in place to make sure that Check Enforcer doesn't spam PRs with comments so the rule will be that if Check Enforcer has ever added a comment to a PR, then it won't ever again.

### CODE REVIEW

**Comment by weshaggard** [comment]
>configuration file to specify the timeout period. The markdown file will be discovered by convention ... CHECKENFORCER-TIMEOUT.md.

Why not have it specified in the CHECKENFORCER config?

**Comment by mitchdenny** [comment]
> > configuration file to specify the timeout period. The markdown file will be discovered by convention ... CHECKENFORCER-TIMEOUT.md.
> 
> Why not have it specified in the CHECKENFORCER config?

The path to the markdown file, or put the markdown content in the file itself? My thinking was that having it in a separate file would just make it cleaner.

**Comment by mitchdenny** [comment]
Moving this over to the feature/check-enforcer-timeout branch on upstream. Closing this PR now and will open a new one once this is further along. I need to do some validation in our staging environment on timers.

**Comment by weshaggard** [comment]
>The path to the markdown file, or put the markdown content in the file itself? My thinking was that having it in a separate file would just make it cleaner.

I was thinking of the path to the markdown file.

**Pull request merged**
