### PR TITLE
[sdk-testgen] shrinkwrap

### PR DESCRIPTION
**Pull request by changlong-liu**
This is a CG fix PR.
Since oav involve manual change to fix CG on async (https://github.com/Azure/oav/pull/782/commits/ba1bab96a4b6b77524ee44a7958eb100dcaca358), testmodeler need to follow same pattern, and this will infect to autorest.typescript too.

In this PR:
1.  Using npm-shrinkwrap.json for testmodeler to froze dependencies to resolve issue: https://github.com/Azure/autorest.typescript/issues/1373. This can prevent autorest.typescript from manual change in package-lock.json.
2. use '--frozen-lockfile' in pnpm to resolve CG issue reported in sdk-testgen pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1526073&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=e05c7f1a-a1e1-5b5c-02b3-7d96b747b23a&l=14776

### CODE REVIEW

**Comment by lirenhe** [comment]
@changlong-liu, could you add some description for this effort?  And do you have the link for the issue you plan to resolve?

**Comment by changlong-liu** [comment]
> @changlong-liu, could you add some description for this effort? And do you have the link for the issue you plan to resolve?

Hi @lirenhe, I added description in top comment. CC to @qiaozha

**Review by tadelesh — APPROVED** [review]

**Comment by tadelesh** [comment]
Could you please add some instructions about how to update/add package to readme for testmodeler?

**Comment by changlong-liu** [comment]
> Could you please add some instructions about how to update/add package to readme for testmodeler?

Yes @tadelesh , doc added, will merge~

**Pull request merged**
