### PR TITLE
Update PythonLanguageService.cs

### PR DESCRIPTION
**Pull request by tjprescott**
Updates to <del>0.3.4</del> 0.3.5.

### CODE REVIEW

**Comment by tjprescott** [comment]
@praveenkuttappan ping on this.

**Comment by tjprescott** [comment]
@praveenkuttappan I just released 0.3.5 of apistubgen. We need to update this to get this update pushed for automatic and PR-based review.

**Comment by maririos** [comment]
@tjprescott Praveen is out today. Let me know if you are blocked or need anything else

**Comment by tjprescott** [comment]
@maririos not blocked. I suspect he will want to wait until the release has happened anyhow.

**Comment by tjprescott** [comment]
Closing as this is part of #4657.

**Pull request closed without merging**
