### PR TITLE
[APIView] Java processor improvements

### PR DESCRIPTION
**Pull request by JonathanGiles**
1. Fix exception when running diagnostics on commented-out Java class: We do not scan compilation units that are missing any primary type (i.e. they are completely commented out).
2. Adding support in the java apiview tooling for comments, and using this to indicate classes that lack any public constructors.
3. Adding support for showing the `@Deprecated` annotation to aid reviewers in identifying the change in state of some API into deprecated API.

### CODE REVIEW

**Comment by JonathanGiles** [comment]
@pakrym fyi

**Comment by JonathanGiles** [comment]
@pakrym A new release of apiview that incorporates these improvements would be appreciated, when you have time.

**Comment by pakrym** [comment]
Done

**Comment by JonathanGiles** [comment]
Thanks @pakrym

**Pull request merged**
