### PR TITLE
Webhook router for EngSys

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR lays down the pipeline for a component that I want to introduce to our engineering system which will receive HTTP messages from various sources (e.g. Azure DevOps and GitHub, but potentially others) and route them to one or more EventHubs.

The idea is that we create a centralized ingestion point for the various fire-and-forget webhooks that get sent and allow multiple jobs to process those events without having to create more HTTP endpoints and more subscriptions.

This PR doesn't contain the implementation for the service, it is just an empty shell right now. Instead this lays down a reusable template which can be used to deploy Azure Functions needed to support the engineering system.

### CODE REVIEW

**Comment by weshaggard** [comment]
What is our primary goal for this? Do we really want to maintain our own set of infrastructure to send telemetry type events for our other tools to use? Won't they still have the same reliability issues as depending on github or devops hooks directly?

**Comment by mitchdenny** [comment]
Creating this HTTP -> EventHubs gateway addresses some lessons that I learned when building Check Enforcer (and in fact I'll be retrofitting Check Enforcer to use this to simplify it considerably).

Check Enforcer as it stands today contains a lot of code that deals with serializing processing against individual PRs and avoiding GitHub rate limiting. At the same time those serialization and rate limiting avoidance results in delays in processing the webhooks which means that Azure Functions will scale out the number of instances it is running to handle the concurrent requests.

So for Check Enforcer dropping those Check Enforcer webhooks into a queue and processing them asynchronously would simplify the code. I figured if I am going to do that for Check Enforcer then I might as well just do it once and set things up so that features like Check Enforcer can just be implemented as a simple daemon that chews on an Event Hub.

One important implementation detail would be that each discrete tool (like Check Enforcer) would own its own Event Hub. They could decide how many partitions are required and what part of the JSON payload (if any) maps to the partition key. This would help them avoid blocking on unrelated PRs (for example).

**Comment by mitchdenny** [comment]
(this PR also contains the build/release pipeline template that I'll ship Check Enforcer over to as well).

**Comment by weshaggard** [comment]
Lets chat more about this in our next 1:1. I want to better understand some of the details.

**Comment by mitchdenny** [comment]
Sure ... I think I'll split the pipeline work into a seperate PR then because I want to get that in for Check Enforcer anyway, and Alex has another PR coming in which can use the same pipeline infrastructure.

**Comment by mitchdenny** [comment]
@weshaggard as I mentioned on our call this morning, here is the baseline implementation of the webhook router. It's been running fine in staging/production environments (deploying off feature branch right now) and I want to rule a line under this where it is right now before I start adding more complex aspects like payload signature validation (which I'll adapt from Check Enforcer).

Here is roughly how it works right now:

Someone who wants to process webhooks asynchronously goes into the app config instance associated with Webhook Router and configures 3 entries:

```
webhookrouter/rules/{route}/payload-type = raw
webhookrouter/rules/{route}/eventhubs-namespace = yournamespace
webhookrouter/rules/{route}/eventhub-name = yourname
```

Once this is configured, the person who wants to receive the webhooks goes into their own EventHubs instance and grants the managed identity of the webhook router service sender/producer access to their hub. Then they go into where the webhooks are published and enter the following URL as the destination for the webhooks.

```
https://webhookrouterenvironmentname.azurewebsites.net/api/route/{route}
```

Once events start flowing the webhook router will use ```{route}``` to lookup the configuration values in the app config service and convert the HTTP request into a message and dispatch it to that EventHub. Authentication is done via MSI so there are no manually managed secrets anyway just yet.

There are a few deficiencies right now which will be addressed in the future:

1. No caching of Azure tokens resulting in unnecessary authentication.
2. No caching of config settings resulting in unnecessary config lookups.
3. No caching of event hub producer clients resulting in unnecessary connections.
4. No GitHub payload verification (mentioned above)
5. No Azure DevOps payload verification.

Still with all that the performance is OK, here is the perf graph:

image

**Pull request merged**
