### PR TITLE
Pipeline generation tool

### PR DESCRIPTION
**Pull request by mitchdenny**
This tool is the first cut at a pipeline generation tool which will streamline the creation of pipelines where we have a ci.yml file present for a particular component. It works by scanning from a starting directory and then checking to see whether the pipeline already exists (it doesn't overwrite it).

The usage is as follows:

```
pipegen --organization https://dev.azure.com/azure-sdk/ --project playground --prefix yourname.net --path C:\Code\azure-sdk-for-net\sdk --patvar PATVAR --endpoint "Azure" --repository Azure/azure-sdk-for-net --open
```

This will then go and create half a dozen or so pipelines in the form ```yourname.net - {component} - ci```. The ```--open``` switch tells the tool to pop a browser for each pipeline it creates and is optional. The ```--repository``` switch is in the form ```{github org}/{github repo}```, and ```--endpoint``` is the name of the service endpoint that will be used to check for the existence of the repo, and that the pipeline will use when it is queued.

In addition to the command above, there is also a ```--whatif``` option that doesn't change anything but will tell you what it would have done. Finally - and most dangerously, there is a ```--destroy``` option which will delete the pipelines that match the naming convention. This can be useful cleaning up from testing but its always a good idea to run that command with the ```--whatif``` option at least once.

The pipelines are setup to run - so if you create them in the playground project they WILL execute as people submit PRs so keep that in mind as it will consume agents out of our agent pool allocation.

Submitting as a draft for now so folks can take a look and check it out. Some refactoring is required, e.g. I'm going to move most of the Azure DevOps calls into a separate class and not pass quite so much state around on method arguments. There are also a few hacks in there which I should clean-up.

### CODE REVIEW

**Comment by danieljurek** [comment]
From offline discussion, a couple small changes here will get us to support integration test pipelines as well.
* Variable groups command line parameter
* Use "conventions" to define search expressions (e.g. "ci.yml" and "tests.yml") and, given a yaml path, return a pipeline definition. The convention used is specified as a command line parameter. The convention could define timing and other specific business logic

**Comment by mitchdenny** [comment]
Haven't implemented the variable group fetching logic yet, logging is non-existent after refactoring. Also it is now much slower - not 100% sure why yet, but I might have a non-cached network call somewhere that I didn't have before.

I'm also considering introducing Lazy<T> for thread-safe initialization of the objects with the goal of then creating all of the definitions concurrently rather than sequentially.

**Comment by mitchdenny** [comment]
@danieljurek I'm about to merge this, but before I do I want to make sure you don't have a branch hanging off it because I'll do a squash if you don't.

**Comment by danieljurek** [comment]
You may squash

**Pull request merged**
