### PR TITLE
Delete obsolete WebhookRouter tool

### PR DESCRIPTION
**Pull request by konrad-jamrozik**
This PR deletes obsolete `WebhookRouter` tool, per this comment: https://github.com/Azure/azure-sdk-tools/pull/4937#pullrequestreview-1214475397

Once this PR is merged, I will also delete the [internal / tools webhook-router](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1651) pipeline.

@hallipr this PR requires your approval per the comment linked above.

Question to all reviewers: Should I reclaim anything from the deleted directory? E.g. the [New-AzureDevOpsRuleCredentials.ps1](https://github.com/Azure/azure-sdk-tools/compare/users/kojamroz/iss_4888_remove_webhook_router?expand=1#diff-a1cfb524d1bf72c307aa4c47dd66bc61dcd14ebfe89fe31bf5e8a94c3238818e) script?

### CODE REVIEW

**Comment by benbp** [comment]
I think it's ok to delete those scripts, even if they may contain some secret devops magic we may need to re-discover in the future.

**Review by weshaggard — COMMENTED** [review]
I defer to @benbp and @hallipr on whether or not we need this any longer.

**Comment by konrad-jamrozik** [comment]
@benbp @hallipr I ran in [Application Insights](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/a18897a6-7e44-457d-9260-f2854c0aca42/resourceGroups/webhookrouterprod/providers/microsoft.insights/components/webhookrouterprod/logs) 

this query, for last 7 days:

```
traces
| where message startswith "Sending event from route" or message startswith "Sent event from route"
| summarize count() by message
```

and found this:

message | count_
-- | --
Sent event from route (cut) to namespace checkenforcerprod with hub name github-webhooks | 15863
Sending event from route (cut) to namespace checkenforcerprod with hub name github-webhooks | 15863
Sending event from route (cut) to namespace issuelabeler with hub name issue-labeler | 1602
Sending event from route (cut) to namespace githubwebhooks with hub name githubwebhooks | 2934
Sent event from route (cut) to namespace githubwebhooks with hub name githubwebhooks | 2934
Sent event from route (cut) to namespace issuelabeler with hub name issue-labeler | 1602

which I believe it mean it is still in use. I could dig deeper and try to figure out who and where are the recipients of these events, and if they actually do anything with it. But I am curious if you have some additional insights based on this data.

**Comment by konrad-jamrozik** [comment]
Per discussion with @hallipr on Teams:

- we should wind down the consumers of the routed messages before decommissioning the router itself
- additional insight: checkenforcer**staging** hasn't had any outgoing messages in the last 30 days

**Comment by konrad-jamrozik** [comment]
I am closing this PR for now, as there is more work to be done before we can decommission the tool. I captured our findings and work required here:
- #4992

Once the prerequisite work is done, we can re-open this PR.

**Pull request closed without merging**
