### PR TITLE
Move various tools into eng/common directory

### PR DESCRIPTION
**Pull request by chidozieononiwu**
Move the following tools to `eng/common` directory
- create-pull-request.yml
- create-tags-and-git-release.yml
- publish-blobs.yml
- copy-docs-to-blobstorage.ps1

### CODE REVIEW

**Comment by weshaggard** [comment]
I would like to follow the same template structure we use everywhere else under `eng/common`. So can these go into `eng\common\pipelines\templates\steps\`?

**Comment by weshaggard** [comment]
sorry didn't mean to close.

**Comment by weshaggard** [comment]
We should also include the support scripts for these templates under  `eng/common`. For example the git-branch-push.ps1 and Submit-PullRequest.ps1 scripts and any other supporting scripts/files these templates need. We shouldn't end to clone or reference another repo in order to use these templates.

**Comment by chidozieononiwu** [comment]
> I would like to follow the same template structure we use everywhere else under `eng/common`. So can these go into `eng\common\pipelines\templates\steps\`?

Moved yaml files as you suggested

**Pull request merged**
