### PR TITLE
Create tutorial branch automation

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR adds two files, a generic PowerShell script that can be used to create a branch in a GitHub repository using the Git database REST API exposed by GitHub (no cloning or pushing required, because you are just adding a ref to a pre-existing commit sha), and a pipeline to wrap around it.

The reason for this new pipeline is that in the Azure SDK training course for internal teams we need a mechanism to setup a feature branch for them to work from and we want to do that without giving them permissions to create new branches in the repository.

The pipeline is intended to be queued manually and takes a few arguments:

1. Pick list of repos (currently only .NET, Java, Python and JavaScript supported)
2. Alias of the person running the pipeline (not auto detected to allow it to be done by instructors easily).
3. Git reference from which the Git branch is created.

The branch is created in the form ```feature/tutorial/<alias>```. I've validated the script and pipeline against the .NET repo.

### CODE REVIEW

**Comment by weshaggard** [comment]
@mitchdenny what is the end plan for this pipeline? Is it only for our training tutorials or do you have other plans for this?

**Comment by mitchdenny** [comment]
At the moment it's just for training. I can see a need for a general bootstrapoer but training has some unique needs. There is going to be another PR which adds some more training specific features.

**Comment by mitchdenny** [comment]
@weshaggard any other feedback? This one is ready to merge.

**Comment by weshaggard** [comment]
I don't have any issues with what you have here please proceed.

I am a little curious why you wrote a script that invokes github APIs directly instead of just using git command line tools to create the branch. It seems like it would be a pretty simple set of git commands.

**Comment by mitchdenny** [comment]
It means that I don't need to clone the repo :) Saves minutes per invocation. The execution time on this is about 15-20 seconds (in total). If I had more time to spend on it I probably wouldn't have setup a little form that submitted to a queue and just processed it in a function (reducing the time to 1-2 seconds :P).

**Pull request merged**
