### PR TITLE
add readme copy to docs script

### PR DESCRIPTION
**Pull request by maggiepint**
Adds script for copying library readme files to docs with added version identifiers in the title.

### CODE REVIEW

**Comment by weshaggard** [comment]
@scbedd do you expect to use this as part of the release process for each language? If so then keeping it in eng/common/scripts makes sense but if you it is part of some other process then we should probably not put it under eng/common.

**Comment by scbedd** [comment]
@weshaggard I'm using it as the basis for the automation that will be fired from each individual release process. This script is the common piece that moves the code. The release processes will contain any language-specific pieces..

**Pull request merged**
