### PR TITLE
Used ScheduledPurgeDate for both KV, MHSM

### PR DESCRIPTION
**Pull request by heaths**
The previous property was calculated so didn't exist from the REST-based
call. Also updated the api-version to the latest stable control plane
version.

### CODE REVIEW

**Comment by mikeharder** [comment]
@heaths: Before merging this PR, I'd like to try running the cleanup pipeline using this PR.

**Review by mikeharder — CHANGES_REQUESTED** [review]
Before merging this PR, I'd like to try running the cleanup pipeline using this PR.

**Review by mikeharder — APPROVED** [review]

**Comment by mikeharder** [comment]
Fix prevents script from failing, but from the logs it appears we still need to do more to actually delete/purge the resources.

**Comment by heaths** [comment]
> Fix prevents script from failing, but from the logs it appears we still need to do more to actually delete/purge the resources.

The script runs on a schedule as well, so it will keep trying and when the purge date expires, they will finally get cleaned up on the next run. That's how it was designed and has been working. What's concerning is how many vaults and HSMs have purge protection enabled. It should almost never be necessary. I started a thread internally to address going forward.

**Comment by heaths** [comment]
I thought it was supposed to merge automatically once the final pipeline was approved.

**Pull request merged**
