### PR TITLE
ADO extension placeholder

### PR DESCRIPTION
**Pull request by mitchdenny**
Creating an ADO extension placeholder. If we want to look at using APIview as an approval gate (based on Ted's email thread) then the way to do it is to create a server side check which forms part of the conditions for a deployment job. There are a few other scenarios that I would like to experiment with server-side jobs as well so it makes sense to create a proper extension with a build/release lifecycle.

### CODE REVIEW

**Comment by weshaggard** [comment]
I'm fine if you want to add this as a example but at this point I'm not sure we will use it for anything yet and if we do I'd be interested to understand what scenarios we would need a custom task over just doing a template in yml.

**Comment by mitchdenny** [comment]
You need a task extension when you want automate an approval gate. For example, if we want to block release of a package when a new groupId:artifactId is introduced, you add a custom server-side task for this which is polled periodically rather than actually running a pipeline.

**Comment by weshaggard** [comment]
Why couldn't we also block the release by failing the release step if the package name isn't approved. Similar to what we do for ApiView or any other linting steps.

**Comment by mitchdenny** [comment]
We can do that too, although you'd probably want to insert it to the tag repo step so we didn't burn a VM for it each time. I'll close this out for now since it seems like we are going down the script route.

**Pull request closed without merging**
