### PR TITLE
Resolve Error in CSharpLanguageService

### PR DESCRIPTION
**Pull request by chidozieononiwu**

### CODE REVIEW

**Comment by JoshLove-msft** [comment]
When I tested this out in my [branch](https://github.com/JoshLove-msft/azure-sdk-tools/tree/apiview-dummy-review), I hit this exception when attempting to view the newly created Api View created from https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN0I8TQ9327U", Request id "0HN0I8TQ9327U:00000004": An unhandled exception was thrown by the application.
      System.InvalidOperationException: The 'Microsoft.AspNetCore.Mvc.ViewFeatures.Infrastructure.DefaultTempDataSerializer' cannot serialize an object of type 'APIViewWeb.ReviewCommentsModel'.
         at Microsoft.AspNetCore.Mvc.ViewFeatures.Infrastructure.DefaultTempDataSerializer.Serialize(IDictionary`2 values)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.CookieTempDataProvider.SaveTempData(HttpContext context, IDictionary`2 values)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary.Save()
         at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.OnStarting(HttpContext httpContext)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<FireOnStarting>g__ProcessEvents|241_0(HttpProtocol protocol, Stack`1 events)
```

**Comment by JoshLove-msft** [comment]
> > When I tested this out in my [branch](https://github.com/JoshLove-msft/azure-sdk-tools/tree/apiview-dummy-review), I hit this exception when attempting to view the newly created Api View created from https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage:
> > ```
> > fail: Microsoft.AspNetCore.Server.Kestrel[13]
> >       Connection id "0HN0I8TQ9327U", Request id "0HN0I8TQ9327U:00000004": An unhandled exception was thrown by the application.
> >       System.InvalidOperationException: The 'Microsoft.AspNetCore.Mvc.ViewFeatures.Infrastructure.DefaultTempDataSerializer' cannot serialize an object of type 'APIViewWeb.ReviewCommentsModel'.
> >          at Microsoft.AspNetCore.Mvc.ViewFeatures.Infrastructure.DefaultTempDataSerializer.Serialize(IDictionary`2 values)
> >          at Microsoft.AspNetCore.Mvc.ViewFeatures.CookieTempDataProvider.SaveTempData(HttpContext context, IDictionary`2 values)
> >          at Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary.Save()
> >          at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.OnStarting(HttpContext httpContext)
> >          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<FireOnStarting>g__ProcessEvents|241_0(HttpProtocol protocol, Stack`1 events)
> > ```
> 
> The issue with that package is that it contains no `.dll` file so the parser has nothing to create the tokens from. Maybe its best to not create the review at all.

Agreed, but this error was hit _after_ implementing the fix to use a dummy review. The error is about the ReviewCommentsModel. FWIW I was attempting to address this issue - https://github.com/Azure/azure-sdk-tools/issues/6663

**Comment by chidozieononiwu** [comment]
> > > When I tested this out in my [branch](https://github.com/JoshLove-msft/azure-sdk-tools/tree/apiview-dummy-review), I hit this exception when attempting to view the newly created Api View created from https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage:
> > > ```
> > > fail: Microsoft.AspNetCore.Server.Kestrel[13]
> > >       Connection id "0HN0I8TQ9327U", Request id "0HN0I8TQ9327U:00000004": An unhandled exception was thrown by the application.
> > >       System.InvalidOperationException: The 'Microsoft.AspNetCore.Mvc.ViewFeatures.Infrastructure.DefaultTempDataSerializer' cannot serialize an object of type 'APIViewWeb.ReviewCommentsModel'.
> > >          at Microsoft.AspNetCore.Mvc.ViewFeatures.Infrastructure.DefaultTempDataSerializer.Serialize(IDictionary`2 values)
> > >          at Microsoft.AspNetCore.Mvc.ViewFeatures.CookieTempDataProvider.SaveTempData(HttpContext context, IDictionary`2 values)
> > >          at Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary.Save()
> > >          at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.OnStarting(HttpContext httpContext)
> > >          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<FireOnStarting>g__ProcessEvents|241_0(HttpProtocol protocol, Stack`1 events)
> > > ```
> > 
> > 
> > The issue with that package is that it contains no `.dll` file so the parser has nothing to create the tokens from. Maybe its best to not create the review at all.
> 
> Agreed, but this error was hit _after_ implementing the fix to use a dummy review. The error is about the ReviewCommentsModel. FWIW I was attempting to address this issue - #6663

Yes, that the error. But the real issue is that the codeFile is empty so noting for the app to show. I have added logic to handle the case where the codeFile is empty. But perhaps we should not be adding the Dummy Review in the first place. Either way I think we can merge this and consider it done.

**Comment by JoshLove-msft** [comment]
> Yes, that the error. But the real issue is that the codeFile is empty so noting for the app to show. I have added logic to handle the case where the codeFile is empty. But perhaps we should not be adding the Dummy Review in the first place. Either way I think we can merge this and consider it done.

Makes sense to me.

**Review by JoshLove-msft — APPROVED** [review]

**Pull request merged**
