### PR TITLE
Add identity access config tool

### LINKED ISSUE #5792: Automate OIDC enablement for github actions
Across our repositories we are planning on using github's OIDC with azure in order to avoid storing any credentials in github. This process should be somewhat automated and/or config based. See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect for more details.

Rough steps to set this up manually, e.g. for access to a keyvault (the role assignment role and scope determine the access):

```
az ad app create --display-name <app name>
az ad sp create --id <app id>

az role assignment create --role "Key Vault Secrets User" --subscription <subscription> --assignee-object-id  <sp oid> --assignee-principal-type ServicePrincipal --scope /subscriptions/<subscription>/resourceGroups/<secrets resource group>/providers/Microsoft.KeyVault/vaults/<keyvault name>

az rest --method POST --uri "https://graph.microsoft.com/beta/applications/<app oid>/federatedIdentityCredentials" --body '{"name":"<cred name>","issuer":"https://token.actions.githubusercontent.com","subject":"repo:<repository e.g. azure/azure-sdk-tools>:ref:refs/heads/main","description":"OIDC for main","audiences":["api://AzureADTokenExchange"]}'
```

Then add secrets to the github repository via Settings -> Security/Secrets and Variables -> Actions -> New Repository Secret. Add `AZURE_CLIENT_ID` (equals the service principle app id from above), `AZURE_SUBSCRIPTION_ID` and `AZURE_TENANT_ID` as secrets, though the values themselves are not sensitive.

From there, you can log in to az in the github workflow and consume the secrets. Due to the above scoping from the `az rest` call this will only be authorized running in the main branch. You can also scope by job_workflow_ref or environment (and add the secrets to a github environment instead) if branch scoping isn't desired:

```
- name: 'Az CLI login'
  if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
  uses: azure/login@v1
  with:
    client-id: ${{ secrets.AZURE_CLIENT_ID }}
    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

Related to https://github.com/Azure/azure-sdk-tools/issues/5789

### PR DESCRIPTION
**Pull request by benbp**
Resolves #5792

This PR adds a tool to manage AAD identities and their access configs (RBAC and federated identity credentials) in a declarative fashion. See [access-config.json](https://github.com/benbp/azure-sdk-tools/blob/ae6871eec7c229ee809bd21857873e7befb4f887/tools/access-manager/tests/test-configs/access-config.json) for an example config.

I wanted to get this up for initial design review, but three things are still missing that I am adding next:

1. Merging this with the [secret rotation](https://github.com/Azure/azure-sdk-tools/tree/main/tools/secret-rotation) so we have a single tool for secret management. We will also want to be able to update rotation configs for when this tool creates new service principals.
2. Syncing RBAC role assignments with the config. Right now we only add. Federated Identity Credentials are currently synced (if you delete one in the config, we will delete it in MS Graph).
3. Getting RBAC working for resource group scopes. Currently it works for my main use case which was KeyVault RBAC roles, but with a group assignment I still get the following error message: `Tenant ID, application ID, principal ID, and scope are not allowed to be updated.`

The tool output looks like this:

```
⇉ ⇉ ⇉ dotnet run --project ./src  -- ./config-gh-actions-no-group.json                                                                                                                      Using config -> /home/ben/sdk/azure-sdk-tools/tools/access-manager/config-gh-actions-no-group.json                                                                                                                                                                                                                                                                                      ---
AppDisplayName -> bebroder-access-manager-test3
FederatedIdentityCredentials ->
    Audiences: api://azureadtokenexchange
    Description: event processor oidc main tools
    Issuer: https://token.actions.githubusercontent.com
    Name: githubactionscredential-tools-main-test1
    Subject: repo:benbp/azure-sdk-tools:ref:refs/heads/main

RoleBasedAccessControls ->
    Role: Key Vault Secrets User
    Scope: /subscriptions/faa080af-c1d8-40ad-9cce-e1a450ca5b57/resourceGroups/rg-bebroder-acess-test/providers/Microsoft.KeyVault/vaults/bebroderaccesstest


Looking for app with display name bebroder-access-manager-test3...
Found bebroder-access-manager-test3 with AppId 5a1a1514-86a5-43c2-b06c-d3b808cabaac and ObjectId 071ffc47-9ac7-45a3-ae21-336ce69c1b23
Found existing service principal with object id '3efca478-31c4-44f9-b2c6-cf7a5ad2708d' for app '5a1a1514-86a5-43c2-b06c-d3b808cabaac'
Found role 'Key Vault Secrets User' with id '4633458b-17de-408a-b874-0445c86b69e6'
Creating role assignment for principal '3efca478-31c4-44f9-b2c6-cf7a5ad2708d' with role 'Key Vault Secrets User' in scope '/subscriptions/faa080af-c1d8-40ad-9cce-e1a450ca5b57/resourceGroups/rg-bebroder-acess-test/providers/Microsoft.KeyVault/vaults/bebroderaccesstest'...
Created role assignment for principal '3efca478-31c4-44f9-b2c6-cf7a5ad2708d' with role 'Key Vault Secrets User' in scope '/subscriptions/faa080af-c1d8-40ad-9cce-e1a450ca5b57/resourceGroups/rg-bebroder-acess-test/providers/Microsoft.KeyVault/vaults/bebroderaccesstest'
Syncing federated identity credentials for bebroder-access-manager-test3
Listing federated identity credentials for app 5a1a1514-86a5-43c2-b06c-d3b808cabaac...
Found 1 federated identity credentials ->
    Audiences: api://azureadtokenexchange
    Description: event processor oidc main tools
    Issuer: https://token.actions.githubusercontent.com
    Name: githubactionscredential-tools-main-test1
    Subject: repo:benbp/azure-sdk-tools:ref:refs/heads/main

Updated federated identity credentials for app bebroder-access-manager-test3 - 1 unchanged, 0 removed, 0 created
```

### CODE REVIEW

**Comment by weshaggard** [comment]
As we chatted lets try to add this to the secret rotation tool and lets also add some MD docs for it.

**Comment by benbp** [comment]
@weshaggard README added. As I mentioned I'd prefer if we can keep this PR review separate from the one that pulls in both tools to a common CLI, because I think that's a change that warrants its own PR discussion given that it will affect how we write our tooling in general.

**Comment by weshaggard** [comment]
As we chatted in our last 1:1 lets go ahead and move this as a sub command into the secrets cli.

**Comment by benbp** [comment]
> As we chatted in our last 1:1 lets go ahead and move this as a sub command into the secrets cli.

@weshaggard done. Now it's like:

```
secrets sync-access -f my-access-config.json  # new command
secrets rotate -c ./plans/
```

I have not merged the plans themselves, not sure if we want to do that now or later or never.

FYI @hallipr this PR will also require me updating the schema references in our internal repo plans to `secret-management` from `secret-rotation`.

**Review by weshaggard — APPROVED** [review]
Looks reasonable overall.

**Comment by weshaggard** [comment]
Lets be sure to update the pipeline and get it triggered on these changes.

**Pull request merged**
