### PR TITLE
Add "weekly" convention to pipeline generator

### LINKED ISSUE #1025: Weekly test pipelines prototype
Run weekly live tests against additional clouds. Automate generation of pipelines.

### PR DESCRIPTION
**Pull request by danieljurek**
Fixes #1025

### CODE REVIEW

**Comment by weshaggard** [comment]
The changes here look reasonable but before we move forward with enabling this generally across the board I'd like to make sure we have the correct conventions for things here. As it stands we will essentially have a duplicated pipeline with the name "- tests-weekly" instead of "- tests" but we haven't really setup any convention that would allow people to easily fork their test matrix based on that. While they could check the pipeline name I'd prefer that we don't have those sorts of checks all over our yml files but instead we have it localized in one place that defines some variables that can be used. We could also have the generator set those as parameters in the pipelines we create.

**Comment by mitchdenny** [comment]
I'm still lamenting the fact that we haven't managed to converge the live testing and nightly CI builds in some fashion. Even if we just bolted on the live test structure that has been established to the main CI run.

**Comment by mitchdenny** [comment]
(I should note that is a much larger conversation than this PR though :P)

**Comment by weshaggard** [comment]
I agree @mitchdenny I still want to combine the tests and ci yml files together and just control what runs based on the pipeline that we are triggering.

**Comment by weshaggard** [comment]
@mitchdenny I should also call out that we are combining these for C++ https://github.com/Azure/azure-sdk-for-cpp/pull/608 as we are bringing them online for the first time.

**Comment by mitchdenny** [comment]
@benbp I think you are taking this onwards? This change LGTM, I hadn't reviewed because it was in draft.

**Review by mitchdenny — APPROVED** [review]

**Comment by benbp** [comment]
Yes @mitchdenny. I need to loop back and merge.

**Comment by benbp** [comment]
Rebased, and tested. Still works! :D

**Comment by weshaggard** [comment]
@benbp do you plan to manually run this as you on-board new repo's for now? Eventually we should get it added to https://github.com/Azure/azure-sdk-tools/blob/master/eng/pipelines/pipeline-generation.yml which is our daily generation run.

**Comment by benbp** [comment]
@weshaggard  https://github.com/Azure/azure-sdk-tools/issues/1234

**Pull request merged**
