### PR TITLE
Revert `Azure.ClientSdk.Analyzers` library to target `netstandard2.0` instead of `net6.0`.

### PR DESCRIPTION
**Pull request by konrad-jamrozik**
**UPDATE** 1/13/2023: this PR is required as it broke things. See:
- https://github.com/Azure/azure-sdk-tools/pull/5048#issuecomment-1382298227
- https://github.com/Azure/azure-sdk-tools/pull/5029/files#r1069929465

**UPDATE** 1/4/2023: I decided to abandon this PR. See [my comment below](https://github.com/Azure/azure-sdk-tools/pull/5048#issuecomment-1371768721) why.

This PR reverts changes in:

- #5029

plus adds a comment why.

### CODE REVIEW

**Comment by konrad-jamrozik** [comment]
@weshaggard on second thought, I think we should keep it to `net6.0`. I've read more about it.

`netstandard` is obsolete, replaced by .net6.0: https://learn.microsoft.com/en-us/dotnet/standard/net-standard

Per this [blog post](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/):

> .NET 5 and all future versions will always support .NET Standard 2.1 and earlier. The only reason to retarget from .NET Standard to .NET 5 is to gain access to more runtime features, language features, or APIs. So, you can think of .NET 5 as .NET Standard vNext.

**Comment by weshaggard** [comment]
In general, if we have all the APIs we need in .NET Standard 2.0 it is generally recommended to target that for libraries. I agree for these libraries we likely don't need to worry about this wider reach but all things being equal I still tend to recommend targeting .NET Standard 2.0 unless there are APIs in later versions you need to consume.

If we haven't released a package yet with the new .NET 6.0 target then I'd still move these back to .NET Standard 2.0 but if we have already released and started consuming a new package with .NET 6.0 then I can accept sticking with that as long as we don't find a use case where we need to target older frameworks.

**Comment by konrad-jamrozik** [comment]
> In general, if we have all the APIs we need in .NET Standard 2.0 it is generally recommended to target that for libraries. I agree for these libraries we likely don't need to worry about this wider reach but all things being equal I still tend to recommend targeting .NET Standard 2.0 unless there are APIs in later versions you need to consume.
> 
> If we haven't released a package yet with the new .NET 6.0 target then I'd still move these back to .NET Standard 2.0 but if we have already released and started consuming a new package with .NET 6.0 then I can accept sticking with that as long as we don't find a use case where we need to target older frameworks.

@weshaggard both of the packages have been published already:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2083477&view=results

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2083478&view=results

I found one case where move to `net6.0` makes things a little bit cleaner:

``` csharp
.FirstOrDefault(
    entry => Matches(targetPath, entry), 
    // assert: none of the codeownersEntries matched targetPath
    new CodeOwnerEntry());
```

When reverted to `netstandard2.0` I get:

image

So I will keep it to `net6.0` per you being OK with it given the packages were published. However, of course I will remember your general guidance going forward. Sorry again for the too-aggressive update!

**Comment by heaths** [comment]
This should probably be reopened, per internal thread, since it's breaking track 2 SDK builds. Our SDKs will "always" target netstandard2.0 at a minimum. We have no plans at this time to upgrade as there's really no need, especially now that we'll start multi-targeting as needed, starting with `netstandard2.0;net461` by default for build-time benefits. Some libraries like Key Vault will be taking advantage of this to work around the few "lies" that net461 supports netstandard2.0, of which the majority of those few APIs not in netstandard2.0 are in `System.Security.Cryptography` that the KV libraries use.

**Review by weshaggard — APPROVED** [review]

**Review by heaths — APPROVED** [review]

**Pull request merged**
