### PR TITLE
Sdk automation branch cleanup

### PR DESCRIPTION
**Pull request by dw511214992**
It's not good to add specific logic to  `branch-cleanup.yml` to cleanup branches created by sdk automation pipeline. So, I create a new tool to cleanup the branches.

The logic to cleanup branches in this tool is:
1. Get all open PRs in sdk repo.
1. Check whether each sdk PR meets the following requirements:
   a. PR's creator is `azure-sdk`.
   b. PR's source branch name is prefixed with `sdkAuto`.
   c. The corresponding swagger PR is merged/closed.
1. Close the sdk PR and delete the source branch if it meets all conditions.

### CODE REVIEW

**Comment by weshaggard** [comment]
As best I can tell your update only does one extra layer of clean-up above what branch-cleanup.yml does today which is check to see if a Swagger PR that created this PR has been closed and if so it will close the language PR and then it will also delete the branch. 

This exact scenario is something that we need for our eng/common sync PR clean-up as well. Can you please work with @sima-zhu to try and consolidate this functionality in a more generic way so we can share it with the existing branch-cleanup.yml and only have one pipeline that is cleaning up branches and old PRs.

**Comment by sima-zhu** [comment]
@dw511214992 The criteria is clear to me. Can I learn why the sdk PR cannot close/merge automatically after swagger PR merged? How do we merge the swagger PR currently, manually or through pipeline?

**Comment by weshaggard** [comment]
@sima-zhu the swagger PR is closed manually when things get merged. Today there isn't a good place to close the PR's we create. 

Thinking about this a little more I think we could extend our existing clean-up to do the following:

1) Find all branches matching a particular regex pattern.
2) If that branch name pattern as a group called "prnumber" (i.e. `sync-eng/common-.*-(<prnumber>\d+)`
3) We can use that prnumber and plug it into a template like `https://github.com/Azure/azure-sdk-tools/pull/$prnumber` or specs PR in the case of swagger.
4) Once you find the PR you can check the status of that related PR (i.e. closed, merged, open, etc) to decide whether or not to delete the branch and any associated PRs in the language repos.

**Comment by dw511214992** [comment]
close it because it's handled in #3342

**Pull request closed without merging**
