### PR TITLE
assign issue when Test-Proxy label is used

### PR DESCRIPTION
**Pull request by mario-guerra**

### CODE REVIEW

**Review by jsquire — APPROVED** [review]
I'm good with approving this for now, but once the EngSys replacement for Fabric Bot is ready, this will need to move to CODEOWNERS in order for it to be included for automated triage.

**Comment by mario-guerra** [comment]
Thanks @jsquire. Once the Fabric Bot replacement is ready, will the move to CODEOWNERS happen automagically or will it require a manual change?

**Comment by jsquire** [comment]
It will require manual updates.   We do not have a fully automated triage process today and team assignments are manual so there's no existing data to convert.   We'll need to create a new set for team-owned labels in all repositories.

**Comment by mario-guerra** [comment]
Thanks again @jsquire. I see that checkenforcer is listed as pending but when I click through the details it shows as completed. Is there a snag in the update logic or does it just take time?

**Comment by jsquire** [comment]
Checkenforcer doesn't play nice when there's not code being updated.   It needs to be manually overridden for these kinds of assets.

**Comment by mario-guerra** [comment]
@jsquire can I make the change to CODEOWNERS now without messing anything up? I see Scott B and Mike H are already code owners for the test proxy, I would just add myself to the list.

**Comment by jsquire** [comment]
You're welcome to update it, but that will just assign you as a reviewer for PRs.   The structure that will be necessary doesn't exist today and the final format is not yet finalized.

**Comment by kurtzeborn** [comment]
@jsquire is this a feature (email notifications) be something we add to your gist that @JimSuplizio is working off of?  Is Mario the first to do this (to your knowledge) using FabricBot?

**Comment by jsquire** [comment]
Email notifications are automatic in GitHub when assignments/mentions take place.   Part of the bot workflow will be fully automating triage, so once we have the needed functionality, registering as an owner will cause assignment and email notification.

**Pull request merged**
