### PR TITLE
Move SnippetGenrator to Tools Directory

### PR DESCRIPTION
**Pull request by chidozieononiwu**
- Move Snippet Generator to the tools directory.
- Add pipeline configuration for releasing SnippetGenerator as tools package.

### CODE REVIEW

**Comment by pakrym** [comment]
The CI doesn't seem to be packing or testing the tool.

```
Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored D:\a\1\s\src\dotnet\Azure.ClientSdk.Analyzers\Azure.ClientSdk.Analyzers\Azure.ClientSdk.Analyzers.csproj (in 36.58 sec).
  Restored D:\a\1\s\src\dotnet\Azure.ClientSdk.Analyzers\Azure.ClientSdk.Analyzers.Tests\Azure.ClientSdk.Analyzers.Tests.csproj (in 36.8 sec).
  Azure.ClientSdk.Analyzers -> D:\a\1\s\artifacts\bin\Azure.ClientSdk.Analyzers\Debug\netcoreapp2.1\Azure.ClientSdk.Analyzers.dll
  Azure.ClientSdk.Analyzers.Tests -> D:\a\1\s\artifacts\bin\Azure.ClientSdk.Analyzers.Tests\Debug\netcoreapp2.1\Azure.ClientSdk.Analyzers.Tests.dll
  Successfully created package 'D:\a\1\a\Azure.ClientSdk.Analyzers.0.1.1-dev.20210727.1.nupkg'.
  Successfully created package 'D:\a\1\a\Azure.ClientSdk.Analyzers.0.1.1-dev.20210727.1.snupkg'.
Finishing
```

```
"C:\Program Files\dotnet\dotnet.exe" test D:\a\1\s\dotnet.proj --logger trx
  Determining projects to restore...
  Restored D:\a\1\s\src\dotnet\Azure.ClientSdk.Analyzers\Azure.ClientSdk.Analyzers\Azure.ClientSdk.Analyzers.csproj (in 30.31 sec).
  Restored D:\a\1\s\src\dotnet\Azure.ClientSdk.Analyzers\Azure.ClientSdk.Analyzers.Tests\Azure.ClientSdk.Analyzers.Tests.csproj (in 32.44 sec).
  Azure.ClientSdk.Analyzers -> D:\a\1\s\artifacts\bin\Azure.ClientSdk.Analyzers\Debug\netcoreapp2.1\Azure.ClientSdk.Analyzers.dll
  Azure.ClientSdk.Analyzers.Tests -> D:\a\1\s\artifacts\bin\Azure.ClientSdk.Analyzers.Tests\Debug\netcoreapp2.1\Azure.ClientSdk.Analyzers.Tests.dll
Test run for D:\a\1\s\artifacts\bin\Azure.ClientSdk.Analyzers.Tests\Debug\netcoreapp2.1\Azure.ClientSdk.Analyzers.Tests.dll (.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Results File: D:\a\1\s\src\dotnet\Azure.ClientSdk.Analyzers\Azure.ClientSdk.Analyzers.Tests\TestResults\VssAdministrator_fv-az92-698_2021-07-27_17_07_55.trx

Passed!  - Failed:     0, Passed:   192, Skipped:     0, Total:   192, Duration: 6 s - Azure.ClientSdk.Analyzers.Tests.dll (netcoreapp2.1)
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting

```

**Comment by weshaggard** [comment]
@pakrym what do you mean by testing the tool? It is running the unit tests and it does call the pack command to produce the package. It isn't running the tool from the package but I'm not sure we need to do that in this process.

**Comment by pakrym** [comment]
>It is running the unit tests 

Yep, I was talking about unit tests.

**Comment by weshaggard** [comment]
Ah it doesn't look like it triggered the correct pipeline. @chidozieononiwu did you create the new pipeline for your ci.yml? It is probably also worth figuring out why it triggered that pipeline.

**Comment by chidozieononiwu** [comment]
> Ah it doesn't look like it triggered the correct pipeline. @chidozieononiwu did you create the new pipeline for your ci.yml?

I created the pipeline that published to the azure-sdk-for-net DevOps feed.

**Pull request merged**
