### PR TITLE
Use updated variable group

### PR DESCRIPTION
**Pull request by danieljurek**
New variable group based on the engsys vault instead of the test vault.

### CODE REVIEW

**Comment by weshaggard** [comment]
FYI @sima-zhu as I know you are starting to look at how we can share these variable group ids.
@danieljurek I assume you are aware you need to also update the prepare-pipelines.yml in the Cpp repo.

**Comment by danieljurek** [comment]
> @danieljurek I assume you are aware you need to also update the prepare-pipelines.yml in the Cpp repo.


I am now :)

**Comment by danieljurek** [comment]
prepare-pipelines.yml update -- https://github.com/Azure/azure-sdk-for-cpp/pull/3459

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
